let URL_APIC, URL_APIP, URL_APIR, URL_APIE, URL_APICM, URL_APIA, URL_APIAF, URL_APIPANEL

URL_APIC = process.env.VITE_URL_APIC
URL_APIP = process.env.VITE_URL_APIP
URL_APIR = process.env.VITE_URL_APIR
URL_APIE = process.env.VITE_URL_APIE
URL_APICM = process.env.VITE_URL_APICM
URL_APIA = process.env.VITE_URL_APIA
URL_APIAF = process.env.VITE_URL_APIAF
URL_APIPANEL = process.env.VITE_URL_APIPANEL

export { URL_APIC, URL_APIP, URL_APIR, URL_APIE, URL_APICM, URL_APIA, URL_APIAF, URL_APIPANEL }